#ifndef ENGINE_SCENE_ENUMS
#define ENGINE_SCENE_ENUMS

enum {
    TILECOLLISION_NONE,
    TILECOLLISION_DOWN,
    TILECOLLISION_UP,
};

enum {
    C_NONE,
    C_TOP,
    C_LEFT,
    C_RIGHT,
    C_BOTTOM,
};

enum {
    FLIP_NONE,
    FLIP_X,
    FLIP_Y,
    FLIP_XY,
};

enum {
    CMODE_FLOOR,
    CMODE_LWALL,
    CMODE_ROOF,
    CMODE_RWALL,
};

enum {
    H_TYPE_TOUCH,
    H_TYPE_CIRCLE,
    H_TYPE_BOX,
    H_TYPE_PLAT,
    H_TYPE_HAMMER,
};

#define TILE_FLIPX_MASK 0x80000000U
#define TILE_FLIPY_MASK 0x40000000U
// #define TILE_DIAGO_MASK 0x20000000U
#define TILE_COLLA_MASK 0x30000000U
#define TILE_COLLB_MASK 0x0C000000U
#define TILE_COLLC_MASK 0x03000000U
#define TILE_IDENT_MASK 0x00FFFFFFU // Max. 16777216 tiles

#endif
